# Generated by Django 2.0.4 on 2018-04-28 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QUOTES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Updated_at', models.DateTimeField(auto_now=True)),
                ('fave_by', models.ManyToManyField(related_name='fave', to='login.USER')),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login.USER')),
            ],
        ),
    ]
